### PR TITLE
Providing option to overwrite duplicate keys in FileDataSource

### PR DESCRIPTION
**Pull request by JeffAshton**
Overwriting with new version allows for graceful file rolling.

**Requirements**

- [X] I have added test coverage for new or changed functionality
- [X] I have followed the repository's [pull request submission guidelines](../blob/master/CONTRIBUTING.md#submitting-pull-requests)
- [X] I have validated my changes against all supported platform versions

**Describe the solution you've provided**

I have created an enum of whether to throw on duplicates, or user the latest version.

**Describe alternatives you've considered**

I considered just always overwriting in order the files are defined, but using the latest version makes the most sense to me.

### CODE REVIEW

**Comment by eli-darkly** [comment]
Making this decision based on the flag's `version` property, while it is consistent with how the SDK works in general, means that you can only use this feature if you're putting the complete flag data model in the file, like if you are actually downloading the data from LD; if you prefer to use the simpler `key: value` mode, you're out of luck. Would it work for your purposes to use the file modification time instead (granted that it'd be more complicated to implement, and file times are not necessarily very fine-grained)?

**Comment by JeffAshton** [comment]
So in my particular use case I am downloading the data from LD.  We have many processes and app domains running on the same machine and hoping to use the FileDataSource to reduce the number of open connections.

**Comment by eli-darkly** [comment]
> So in my particular use case I am downloading the data from LD. We have many processes and app domains running on the same machine and hoping to use the FileDataSource to reduce the number of open connections.

Yes, I guessed that that was your use case, since this implementation would only work for someone who is downloading the data from LD (or, less likely, hand-coding the data model). But the reason I raised a concern is that not everyone will be using the thing in that way, and the simplified data model is a usage that we explicitly support so it would be nice to be able to provide similar functionality there.

**Comment by JeffAshton** [comment]
So in your simplified data model, it would use the first definition of the flags, since the versions would all be 0.  Which is nicer then throwing.  Users could then just order the input files to match their model, if they're rolling files.

**Comment by JeffAshton** [comment]
If you're not rolling files, I think duplicates would probably be bad, and should use the throw option.

**Comment by eli-darkly** [comment]
> So in your simplified data model, it would use the first definition of the flags, since the versions would all be 0. Which is nicer then throwing. Users could then just order the input files to match their model, if they're rolling files.

I'm unclear on how they could "order the input files to match their model" in that scenario. Are you suggesting something like: specify file paths "data1.yml" and "data2.yml", start out with everything in data1 and nothing in data2, and every time you're going to update the flags, rename data1 to data2 and put the new data in data1?

I would still like to know if you have an objection to using file modification times.

**Comment by JeffAshton** [comment]
I don't feel like file modification times are the correct solution, given the existing data model having a `version`.  Accidentally touching a file shouldn't change the result.

The rolling procedure I use is:

1. Move current.config to backup.config
2. Write the new current.config  (this is actually a File.Move, but either should work)
3. Delete the backup.config

The `FileDataSource` reads files in order (true today), and if the versions were all the same, ordering  the files [ current.config, backup.config ], then you would always get the latest.

**Comment by JeffAshton** [comment]
Crap, I messed up the branch in Github.  One sec.

**Comment by JeffAshton** [comment]
Fixed.

**Pull request closed without merging**
